# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 389dec03b6b8c46dd19dc6209bb719bf5aeed875a4f38e688ccd19ea4e0dad142b8456761f1d9b1ebc5ae43c84f86e39e2c086727e83ff7e5167df5ea93aa7a5

test:
  secret_key_base: 4e5264d798b04978fbf831bf3789b97d35fd5b40fda337abec1afcd181aabe7ca42b5e9ed1890237ca9bf3f7eccc5bb1272ebaa837437c81cb3b22096f35c36e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
